-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 09:28:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema s2_t1_n1_e2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `s2_t1_n1_e2` ;

-- -----------------------------------------------------
-- Schema s2_t1_n1_e2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `s2_t1_n1_e2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `s2_t1_n1_e2` ;

-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`province` (
  `province_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`province_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`location` (
  `location_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `province` INT NOT NULL,
  PRIMARY KEY (`location_id`),
  CONSTRAINT `fk_location_province1`
    FOREIGN KEY (`province`)
    REFERENCES `s2_t1_n1_e2`.`province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_location_province1_idx1` ON `s2_t1_n1_e2`.`location` (`province` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`client` (
  `client_id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `surnames` VARCHAR(50) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `postal_code` VARCHAR(15) NOT NULL,
  `phone_number` VARCHAR(15) NULL DEFAULT NULL,
  `province` INT NOT NULL,
  `location` INT NOT NULL,
  PRIMARY KEY (`client_id`),
  CONSTRAINT `fk_client_location1`
    FOREIGN KEY (`location`)
    REFERENCES `s2_t1_n1_e2`.`location` (`location_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_client_location1_idx` ON `s2_t1_n1_e2`.`client` (`province` ASC, `location` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`shop` (
  `shop_id` INT NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `postal_code` VARCHAR(15) NOT NULL,
  `location` INT NOT NULL,
  PRIMARY KEY (`shop_id`),
  CONSTRAINT `fk_shop_location1`
    FOREIGN KEY (`location`)
    REFERENCES `s2_t1_n1_e2`.`location` (`location_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_shop_location1_idx` ON `s2_t1_n1_e2`.`shop` (`location` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`employee` (
  `employee_id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `surnames` VARCHAR(25) NOT NULL,
  `NIF` VARCHAR(15) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `cook_or_delivery` VARCHAR(10) NOT NULL,
  `shop` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  CONSTRAINT `fk_employee_shop1`
    FOREIGN KEY (`shop`)
    REFERENCES `s2_t1_n1_e2`.`shop` (`shop_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_employee_shop1_idx` ON `s2_t1_n1_e2`.`employee` (`shop` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`cook`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`cook` (
  `cook_id` INT NOT NULL,
  PRIMARY KEY (`cook_id`),
  CONSTRAINT `fk_cook_employee1`
    FOREIGN KEY (`cook_id`)
    REFERENCES `s2_t1_n1_e2`.`employee` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_cook_employee1_idx` ON `s2_t1_n1_e2`.`cook` (`cook_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`delivery` (
  `delivery_id` INT NOT NULL,
  PRIMARY KEY (`delivery_id`),
  CONSTRAINT `fk_delivery_employee1`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `s2_t1_n1_e2`.`employee` (`employee_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_delivery_employee1_idx` ON `s2_t1_n1_e2`.`delivery` (`delivery_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`product` (
  `product_id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `image` BLOB NOT NULL,
  `type` VARCHAR(10) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`drink` (
  `drink_id` INT NOT NULL,
  PRIMARY KEY (`drink_id`),
  CONSTRAINT `fk_drink_product1`
    FOREIGN KEY (`drink_id`)
    REFERENCES `s2_t1_n1_e2`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_drink_product1_idx` ON `s2_t1_n1_e2`.`drink` (`drink_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`hamburguer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`hamburguer` (
  `hamburguer_id` INT NOT NULL,
  PRIMARY KEY (`hamburguer_id`),
  CONSTRAINT `fk_hamburguer_product1`
    FOREIGN KEY (`hamburguer_id`)
    REFERENCES `s2_t1_n1_e2`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_hamburguer_product1_idx` ON `s2_t1_n1_e2`.`hamburguer` (`hamburguer_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`orders` (
  `order_id` INT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `home_or_shop` VARCHAR(10) NOT NULL,
  `total_price` FLOAT NOT NULL,
  `shop` INT NOT NULL,
  `client` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_orders_shop1`
    FOREIGN KEY (`shop`)
    REFERENCES `s2_t1_n1_e2`.`shop` (`shop_id`),
  CONSTRAINT `fk_orders_client1`
    FOREIGN KEY (`client`)
    REFERENCES `s2_t1_n1_e2`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_orders_shop1_idx` ON `s2_t1_n1_e2`.`orders` (`shop` ASC) VISIBLE;

CREATE INDEX `fk_orders_client1_idx1` ON `s2_t1_n1_e2`.`orders` (`client` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`order_at_home`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`order_at_home` (
  `order_at_home_id` INT NOT NULL,
  `delivery` INT NOT NULL,
  `date_time_delivery` DATETIME NOT NULL,
  PRIMARY KEY (`order_at_home_id`),
  CONSTRAINT `fk_order_at_home_delivery1`
    FOREIGN KEY (`delivery`)
    REFERENCES `s2_t1_n1_e2`.`delivery` (`delivery_id`),
  CONSTRAINT `fk_order_at_home_orders1`
    FOREIGN KEY (`order_at_home_id`)
    REFERENCES `s2_t1_n1_e2`.`orders` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_order_at_home_orders1_idx` ON `s2_t1_n1_e2`.`order_at_home` (`order_at_home_id` ASC) VISIBLE;

CREATE INDEX `fk_order_at_home_delivery1_idx` ON `s2_t1_n1_e2`.`order_at_home` (`delivery` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`order_at_shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`order_at_shop` (
  `order_at_shop_id` INT NOT NULL,
  PRIMARY KEY (`order_at_shop_id`),
  CONSTRAINT `fk_order_at_shop_orders1`
    FOREIGN KEY (`order_at_shop_id`)
    REFERENCES `s2_t1_n1_e2`.`orders` (`order_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_order_at_shop_orders1_idx` ON `s2_t1_n1_e2`.`order_at_shop` (`order_at_shop_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`orders_has_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`orders_has_product` (
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `product_id`),
  CONSTRAINT `fk_orders_has_product_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `s2_t1_n1_e2`.`orders` (`order_id`),
  CONSTRAINT `fk_orders_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `s2_t1_n1_e2`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_orders_has_product_product1_idx` ON `s2_t1_n1_e2`.`orders_has_product` (`product_id` ASC) VISIBLE;

CREATE INDEX `fk_orders_has_product_orders1_idx` ON `s2_t1_n1_e2`.`orders_has_product` (`order_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e2`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e2`.`pizza` (
  `pizza_id` INT NOT NULL,
  `category` INT NOT NULL,
  PRIMARY KEY (`pizza_id`),
  CONSTRAINT `fk_pizza_category1`
    FOREIGN KEY (`category`)
    REFERENCES `s2_t1_n1_e2`.`category` (`category_id`),
  CONSTRAINT `fk_pizza_product1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `s2_t1_n1_e2`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_pizza_product1_idx` ON `s2_t1_n1_e2`.`pizza` (`pizza_id` ASC) VISIBLE;

CREATE INDEX `fk_pizza_category1_idx` ON `s2_t1_n1_e2`.`pizza` (`category` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
