-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 09:47:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema s2_t1_n1_e1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `s2_t1_n1_e1` ;

-- -----------------------------------------------------
-- Schema s2_t1_n1_e1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `s2_t1_n1_e1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `s2_t1_n1_e1` ;

-- -----------------------------------------------------
-- Table `s2_t1_n1_e1`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e1`.`address` (
  `address_id` INT NOT NULL,
  `street` VARCHAR(50) NOT NULL,
  `building_number` INT NOT NULL,
  `floor_number` INT NOT NULL,
  `door_number` INT NOT NULL,
  `city` VARCHAR(25) NOT NULL,
  `postal_code` VARCHAR(15) NOT NULL,
  `country` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e1`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e1`.`client` (
  `client_id` INT NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `phone_number` VARCHAR(15) NULL,
  `email` VARCHAR(50) NOT NULL,
  `registration_date` DATE NOT NULL,
  `recommended_by` INT NULL DEFAULT NULL,
  `address` INT NULL,
  PRIMARY KEY (`client_id`),
  CONSTRAINT `client_ibfk_1`
    FOREIGN KEY (`recommended_by`)
    REFERENCES `s2_t1_n1_e1`.`client` (`client_id`),
  CONSTRAINT `fk_client_address1`
    FOREIGN KEY (`address`)
    REFERENCES `s2_t1_n1_e1`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `recommended_by` ON `s2_t1_n1_e1`.`client` (`recommended_by` ASC) VISIBLE;

CREATE INDEX `fk_client_address1_idx` ON `s2_t1_n1_e1`.`client` (`address` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e1`.`bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e1`.`bill` (
  `bill_id` INT NOT NULL,
  `employee` VARCHAR(50) NOT NULL,
  `date` DATE NOT NULL,
  `total_price` FLOAT NOT NULL,
  `client` INT NOT NULL,
  PRIMARY KEY (`bill_id`),
  CONSTRAINT `fk_bill_client1`
    FOREIGN KEY (`client`)
    REFERENCES `s2_t1_n1_e1`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_bill_client1_idx1` ON `s2_t1_n1_e1`.`bill` (`client` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e1`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e1`.`supplier` (
  `NIF` VARCHAR(15) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `fax_number` VARCHAR(15) NULL DEFAULT NULL,
  `address` INT NOT NULL,
  PRIMARY KEY (`NIF`),
  CONSTRAINT `fk_supplier_address1`
    FOREIGN KEY (`address`)
    REFERENCES `s2_t1_n1_e1`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_supplier_address1_idx` ON `s2_t1_n1_e1`.`supplier` (`address` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e1`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e1`.`brand` (
  `brand_id` INT NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `supplied_by` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`brand_id`),
  CONSTRAINT `brand_ibfk_1`
    FOREIGN KEY (`supplied_by`)
    REFERENCES `s2_t1_n1_e1`.`supplier` (`NIF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `supplied_by` ON `s2_t1_n1_e1`.`brand` (`supplied_by` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n1_e1`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n1_e1`.`glasses` (
  `glasses_id` INT NOT NULL,
  `prescription` INT NOT NULL,
  `frame_type` VARCHAR(15) NOT NULL,
  `frame_colour` VARCHAR(15) NOT NULL,
  `glass_colour` VARCHAR(15) NOT NULL,
  `price` FLOAT NOT NULL,
  `bill` INT NULL DEFAULT NULL,
  `brand` INT NOT NULL,
  PRIMARY KEY (`glasses_id`),
  CONSTRAINT `fk_glasses_bill1`
    FOREIGN KEY (`bill`)
    REFERENCES `s2_t1_n1_e1`.`bill` (`bill_id`),
  CONSTRAINT `fk_glasses_brand1`
    FOREIGN KEY (`brand`)
    REFERENCES `s2_t1_n1_e1`.`brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_glasses_bill1_idx` ON `s2_t1_n1_e1`.`glasses` (`bill` ASC) VISIBLE;

CREATE INDEX `fk_glasses_brand1_idx` ON `s2_t1_n1_e1`.`glasses` (`brand` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
