-- MySQL Script generated by MySQL Workbench
-- Fri Oct 27 13:33:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema s2_t1_n3_e1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `s2_t1_n3_e1` ;

-- -----------------------------------------------------
-- Schema s2_t1_n3_e1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `s2_t1_n3_e1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`payment_method`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment_method` (
  `payment_id` INT NOT NULL,
  `method` ENUM('paypal', 'credit card') NOT NULL,
  PRIMARY KEY (`payment_id`))
ENGINE = InnoDB;

USE `s2_t1_n3_e1` ;

-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`artist` (
  `artist_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `image` BLOB NOT NULL,
  PRIMARY KEY (`artist_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`album` (
  `album_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `album_cover` BLOB NOT NULL,
  `artist` INT NOT NULL,
  PRIMARY KEY (`album_id`),
  CONSTRAINT `fk_album_artist1`
    FOREIGN KEY (`artist`)
    REFERENCES `s2_t1_n3_e1`.`artist` (`artist_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_album_artist1_idx` ON `s2_t1_n3_e1`.`album` (`artist` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`credit_card` (
  `credit_card_id` INT NOT NULL,
  `card_number` INT NOT NULL,
  `expire_date` DATE NOT NULL,
  `safety_code` INT NOT NULL,
  PRIMARY KEY (`credit_card_id`),
  CONSTRAINT `fk_credit_card_payment_method1`
    FOREIGN KEY (`credit_card_id`)
    REFERENCES `mydb`.`payment_method` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_credit_card_payment_method1_idx` ON `s2_t1_n3_e1`.`credit_card` (`credit_card_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`user` (
  `user_id` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `username` VARCHAR(25) NOT NULL,
  `birth_date` DATE NOT NULL,
  `sex` VARCHAR(10) NULL DEFAULT NULL,
  `country` VARCHAR(25) NOT NULL,
  `postal_code` VARCHAR(15) NULL DEFAULT NULL,
  `type` ENUM('free', 'premium') NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`playlist` (
  `playlist_id` INT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `song_number` INT NOT NULL,
  `creation_date` DATE NOT NULL,
  `type` ENUM('active', 'deleted') NOT NULL,
  `user_creator` INT NOT NULL,
  PRIMARY KEY (`playlist_id`),
  CONSTRAINT `fk_playlist_user1`
    FOREIGN KEY (`user_creator`)
    REFERENCES `s2_t1_n3_e1`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_playlist_user1_idx` ON `s2_t1_n3_e1`.`playlist` (`user_creator` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`deleted_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`deleted_playlist` (
  `deleted_playlist_id` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`deleted_playlist_id`),
  CONSTRAINT `fk_deleted_playlist_playlist1`
    FOREIGN KEY (`deleted_playlist_id`)
    REFERENCES `s2_t1_n3_e1`.`playlist` (`playlist_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`subscription` (
  `subscription_id` INT NOT NULL,
  `starting_date` DATE NOT NULL,
  `renewal_date` DATE NOT NULL,
  `premium_user` INT NOT NULL,
  `payment_method` INT NOT NULL,
  PRIMARY KEY (`subscription_id`),
  CONSTRAINT `fk_subscription_user1`
    FOREIGN KEY (`premium_user`)
    REFERENCES `s2_t1_n3_e1`.`user` (`user_id`),
  CONSTRAINT `fk_subscription_payment_method1`
    FOREIGN KEY (`payment_method`)
    REFERENCES `mydb`.`payment_method` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_subscription_user1_idx` ON `s2_t1_n3_e1`.`subscription` (`premium_user` ASC) VISIBLE;

CREATE INDEX `fk_subscription_payment_method1_idx` ON `s2_t1_n3_e1`.`subscription` (`payment_method` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`payment` (
  `order_number` INT NOT NULL,
  `date` DATE NOT NULL,
  `total_price` FLOAT NOT NULL,
  `subscription` INT NOT NULL,
  PRIMARY KEY (`order_number`),
  CONSTRAINT `fk_payment_subscription1`
    FOREIGN KEY (`subscription`)
    REFERENCES `s2_t1_n3_e1`.`subscription` (`subscription_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_payment_subscription1_idx` ON `s2_t1_n3_e1`.`payment` (`subscription` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`paypal` (
  `paypal_id` INT NOT NULL,
  `username` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`paypal_id`),
  CONSTRAINT `fk_paypal_payment_method1`
    FOREIGN KEY (`paypal_id`)
    REFERENCES `mydb`.`payment_method` (`payment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_paypal_payment_method1_idx` ON `s2_t1_n3_e1`.`paypal` (`paypal_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`similar_artists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`similar_artists` (
  `artist1_id` INT NOT NULL,
  `artist2_id` INT NOT NULL,
  PRIMARY KEY (`artist1_id`, `artist2_id`),
  CONSTRAINT `fk_artist_has_artist_artist1`
    FOREIGN KEY (`artist1_id`)
    REFERENCES `s2_t1_n3_e1`.`artist` (`artist_id`),
  CONSTRAINT `fk_artist_has_artist_artist2`
    FOREIGN KEY (`artist2_id`)
    REFERENCES `s2_t1_n3_e1`.`artist` (`artist_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_artist_has_artist_artist2_idx` ON `s2_t1_n3_e1`.`similar_artists` (`artist2_id` ASC) VISIBLE;

CREATE INDEX `fk_artist_has_artist_artist1_idx` ON `s2_t1_n3_e1`.`similar_artists` (`artist1_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`song` (
  `song_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `length` VARCHAR(45) NOT NULL,
  `times_played` INT NOT NULL,
  `album` INT NOT NULL,
  PRIMARY KEY (`song_id`),
  CONSTRAINT `fk_song_album1`
    FOREIGN KEY (`album`)
    REFERENCES `s2_t1_n3_e1`.`album` (`album_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_song_album1_idx` ON `s2_t1_n3_e1`.`song` (`album` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`user_adds_song_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`user_adds_song_playlist` (
  `user_id` INT NOT NULL,
  `active_playlist_id` INT NOT NULL,
  `song_id` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`user_id`, `active_playlist_id`, `song_id`),
  CONSTRAINT `fk_user_adds_song_playlist_playlist1`
    FOREIGN KEY (`active_playlist_id`)
    REFERENCES `s2_t1_n3_e1`.`playlist` (`playlist_id`),
  CONSTRAINT `fk_user_has_active_playlist_song1`
    FOREIGN KEY (`song_id`)
    REFERENCES `s2_t1_n3_e1`.`song` (`song_id`),
  CONSTRAINT `fk_user_has_active_playlist_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `s2_t1_n3_e1`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_user_has_active_playlist_user1_idx` ON `s2_t1_n3_e1`.`user_adds_song_playlist` (`user_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_active_playlist_song1_idx` ON `s2_t1_n3_e1`.`user_adds_song_playlist` (`song_id` ASC) VISIBLE;

CREATE INDEX `fk_user_adds_song_playlist_playlist1_idx` ON `s2_t1_n3_e1`.`user_adds_song_playlist` (`active_playlist_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`user_follows_artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`user_follows_artist` (
  `user_id` INT NOT NULL,
  `artist_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `artist_id`),
  CONSTRAINT `fk_user_has_artist_artist1`
    FOREIGN KEY (`artist_id`)
    REFERENCES `s2_t1_n3_e1`.`artist` (`artist_id`),
  CONSTRAINT `fk_user_has_artist_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `s2_t1_n3_e1`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_user_has_artist_artist1_idx` ON `s2_t1_n3_e1`.`user_follows_artist` (`artist_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_artist_user_idx` ON `s2_t1_n3_e1`.`user_follows_artist` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`user_has_favourite_albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`user_has_favourite_albums` (
  `user_id` INT NOT NULL,
  `album_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `album_id`),
  CONSTRAINT `fk_user_has_album_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `s2_t1_n3_e1`.`album` (`album_id`),
  CONSTRAINT `fk_user_has_album_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `s2_t1_n3_e1`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_user_has_album_album1_idx` ON `s2_t1_n3_e1`.`user_has_favourite_albums` (`album_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_album_user1_idx` ON `s2_t1_n3_e1`.`user_has_favourite_albums` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n3_e1`.`user_has_favourite_songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n3_e1`.`user_has_favourite_songs` (
  `user_id` INT NOT NULL,
  `song_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `song_id`),
  CONSTRAINT `fk_user_has_song_song1`
    FOREIGN KEY (`song_id`)
    REFERENCES `s2_t1_n3_e1`.`song` (`song_id`),
  CONSTRAINT `fk_user_has_song_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `s2_t1_n3_e1`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_user_has_song_song1_idx` ON `s2_t1_n3_e1`.`user_has_favourite_songs` (`song_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_song_user1_idx` ON `s2_t1_n3_e1`.`user_has_favourite_songs` (`user_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
