-- MySQL Script generated by MySQL Workbench
-- Fri Oct 27 12:35:11 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema s2_t1_n2_e1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `s2_t1_n2_e1` ;

-- -----------------------------------------------------
-- Schema s2_t1_n2_e1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `s2_t1_n2_e1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `s2_t1_n2_e1` ;

-- -----------------------------------------------------
-- Table `s2_t1_n2_e1`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n2_e1`.`user` (
  `user_id` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `username` VARCHAR(25) NOT NULL,
  `birth_date` DATE NOT NULL,
  `sex` VARCHAR(15) NULL DEFAULT NULL,
  `country` VARCHAR(25) NOT NULL,
  `postal_code` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s2_t1_n2_e1`.`channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n2_e1`.`channel` (
  `channel_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `creation_date` DATE NOT NULL,
  `user_owner` INT NOT NULL,
  PRIMARY KEY (`channel_id`),
  CONSTRAINT `fk_channel_user1`
    FOREIGN KEY (`user_owner`)
    REFERENCES `s2_t1_n2_e1`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_channel_user1_idx` ON `s2_t1_n2_e1`.`channel` (`user_owner` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n2_e1`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n2_e1`.`video` (
  `video_id` INT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  `size` INT NOT NULL,
  `file_name` VARCHAR(50) NOT NULL,
  `length` INT NOT NULL,
  `thumbnail` BLOB NOT NULL,
  `views` INT NOT NULL,
  `likes` INT NOT NULL,
  `dislikes` INT NOT NULL,
  `state` ENUM('private', 'public', 'unlisted') NOT NULL,
  `date_time` DATETIME NOT NULL,
  `user_author` INT NOT NULL,
  PRIMARY KEY (`video_id`),
  CONSTRAINT `fk_video_user1`
    FOREIGN KEY (`user_author`)
    REFERENCES `s2_t1_n2_e1`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_video_user1_idx` ON `s2_t1_n2_e1`.`video` (`user_author` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n2_e1`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n2_e1`.`comment` (
  `comment_id` INT NOT NULL,
  `text` VARCHAR(100) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `user_author` INT NOT NULL,
  `video` INT NOT NULL,
  PRIMARY KEY (`comment_id`),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_author`)
    REFERENCES `s2_t1_n2_e1`.`user` (`user_id`),
  CONSTRAINT `fk_comment_video1`
    FOREIGN KEY (`video`)
    REFERENCES `s2_t1_n2_e1`.`video` (`video_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_comment_user1_idx` ON `s2_t1_n2_e1`.`comment` (`user_author` ASC) VISIBLE;

CREATE INDEX `fk_comment_video1_idx` ON `s2_t1_n2_e1`.`comment` (`video` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n2_e1`.`label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n2_e1`.`label` (
  `lable_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lable_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `s2_t1_n2_e1`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n2_e1`.`playlist` (
  `playlist_id` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `creation_date` DATE NOT NULL,
  `state` ENUM('private', 'public') NOT NULL,
  `user_creator` INT NOT NULL,
  PRIMARY KEY (`playlist_id`),
  CONSTRAINT `fk_playlist_user1`
    FOREIGN KEY (`user_creator`)
    REFERENCES `s2_t1_n2_e1`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_playlist_user1_idx` ON `s2_t1_n2_e1`.`playlist` (`user_creator` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n2_e1`.`playlist_has_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n2_e1`.`playlist_has_video` (
  `playlist_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`playlist_id`, `video_id`),
  CONSTRAINT `fk_playlist_has_video_playlist1`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `s2_t1_n2_e1`.`playlist` (`playlist_id`),
  CONSTRAINT `fk_playlist_has_video_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `s2_t1_n2_e1`.`video` (`video_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_playlist_has_video_video1_idx` ON `s2_t1_n2_e1`.`playlist_has_video` (`video_id` ASC) VISIBLE;

CREATE INDEX `fk_playlist_has_video_playlist1_idx` ON `s2_t1_n2_e1`.`playlist_has_video` (`playlist_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n2_e1`.`user_rates_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n2_e1`.`user_rates_comment` (
  `user_id` INT NOT NULL,
  `comment_id` INT NOT NULL,
  `rating` ENUM('like', 'dislike') NOT NULL,
  `date_time` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`, `comment_id`),
  CONSTRAINT `fk_user_has_comment_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `s2_t1_n2_e1`.`comment` (`comment_id`),
  CONSTRAINT `fk_user_has_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `s2_t1_n2_e1`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_user_has_comment_comment1_idx` ON `s2_t1_n2_e1`.`user_rates_comment` (`comment_id` ASC) VISIBLE;

CREATE INDEX `fk_user_has_comment_user1_idx` ON `s2_t1_n2_e1`.`user_rates_comment` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n2_e1`.`user_rates_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n2_e1`.`user_rates_video` (
  `user_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `rating` ENUM('like', 'dislike') NOT NULL,
  PRIMARY KEY (`user_id`, `video_id`),
  CONSTRAINT `fk_user_rates_video_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `s2_t1_n2_e1`.`user` (`user_id`),
  CONSTRAINT `fk_user_rates_video_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `s2_t1_n2_e1`.`video` (`video_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_user_rates_video_video1` ON `s2_t1_n2_e1`.`user_rates_video` (`video_id` ASC) VISIBLE;

CREATE INDEX `fk_user_rates_video_user1_idx` ON `s2_t1_n2_e1`.`user_rates_video` (`user_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n2_e1`.`user_subscribes_to_channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n2_e1`.`user_subscribes_to_channel` (
  `user_id` INT NOT NULL,
  `channel_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `channel_id`),
  CONSTRAINT `fk_user_subscribes_to_channel_channel1`
    FOREIGN KEY (`channel_id`)
    REFERENCES `s2_t1_n2_e1`.`channel` (`channel_id`),
  CONSTRAINT `fk_user_subscribes_to_channel_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `s2_t1_n2_e1`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_user_subscribes_to_channel_channel1_idx` ON `s2_t1_n2_e1`.`user_subscribes_to_channel` (`channel_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `s2_t1_n2_e1`.`video_has_labels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `s2_t1_n2_e1`.`video_has_labels` (
  `video_id` INT NOT NULL,
  `lable_id` INT NOT NULL,
  PRIMARY KEY (`video_id`, `lable_id`),
  CONSTRAINT `fk_video_has_labels_Label1`
    FOREIGN KEY (`lable_id`)
    REFERENCES `s2_t1_n2_e1`.`label` (`lable_id`),
  CONSTRAINT `fk_video_has_labels_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `s2_t1_n2_e1`.`video` (`video_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_video_has_labels_Label1_idx` ON `s2_t1_n2_e1`.`video_has_labels` (`lable_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
